<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Bharath" failures="1" tests="7" name="Test" time="0.896" errors="0" timestamp="2025-08-30T08:36:24 IST">
  <testcase classname="testng.framework.concepts.ApplicationTest" name="TestCase4" time="0.012"/>
  <testcase classname="testng.framework.concepts.ApplicationTest" name="TestCase3" time="0.002"/>
  <testcase classname="testng.framework.concepts.ApplicationTest" name="TestCase3" time="0.003"/>
  <testcase classname="testng.framework.concepts.ApplicationTest" name="TestCase1" time="0.006">
    <skipped/>
  </testcase> <!-- TestCase1 -->
  <testcase classname="testng.framework.concepts.ApplicationTest" name="TestCase1" time="0.002">
    <skipped/>
  </testcase> <!-- TestCase1 -->
  <testcase classname="testng.framework.concepts.ApplicationTest" name="TestCase1" time="0.004">
    <failure type="java.lang.AssertionError" message="Test case 1 failed">
      <![CDATA[java.lang.AssertionError: Test case 1 failed
at testng.framework.concepts.ApplicationTest.TestCase1(ApplicationTest.java:28)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- TestCase1 -->
  <testcase classname="testng.framework.concepts.ApplicationTest" name="TestCase2" time="0.0">
    <skipped/>
  </testcase> <!-- TestCase2 -->
</testsuite> <!-- Test -->
