<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Bharath" failures="1" tests="7" name="testng.framework.concepts.ApplicationTest" time="0.038" errors="0" timestamp="2025-08-30T08:36:25 IST" skipped="3">
  <testcase classname="testng.framework.concepts.ApplicationTest" name="TestCase4" time="0.013"/>
  <system-out/>
  <testcase classname="testng.framework.concepts.ApplicationTest" name="TestCase3" time="0.004"/>
  <system-out/>
  <testcase classname="testng.framework.concepts.ApplicationTest" name="TestCase3" time="0.004"/>
  <system-out/>
  <testcase classname="testng.framework.concepts.ApplicationTest" name="TestCase2" time="0.002">
    <skipped/>
  </testcase> <!-- TestCase2 -->
  <system-out/>
  <testcase classname="testng.framework.concepts.ApplicationTest" name="TestCase1" time="0.003">
    <skipped/>
  </testcase> <!-- TestCase1 -->
  <system-out/>
  <testcase classname="testng.framework.concepts.ApplicationTest" name="TestCase1" time="0.008">
    <skipped/>
  </testcase> <!-- TestCase1 -->
  <system-out/>
  <testcase classname="testng.framework.concepts.ApplicationTest" name="TestCase1" time="0.004">
    <failure message="Test case 1 failed" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test case 1 failed
at org.testng.Assert.fail(Assert.java:99)
at testng.framework.concepts.ApplicationTest.TestCase1(ApplicationTest.java:28)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- TestCase1 -->
  <system-out/>
</testsuite> <!-- testng.framework.concepts.ApplicationTest -->
